/// Flutter icons BPM_Social_Icons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BPM_Social_Icons
///      fonts:
///       - asset: fonts/BPM_Social_Icons.ttf
///
/// 
///
// import 'package:flutter/widgets.dart';

// class BPM_Social_Icons {
//   BPM_Social_Icons._();

//   static const _kFontFam = 'BPM_Social_Icons';

//   static const IconData facebook = const IconData(0xe800, fontFamily: _kFontFam);
//   static const IconData instagram = const IconData(0xe801, fontFamily: _kFontFam);
//   static const IconData youtube = const IconData(0xe802, fontFamily: _kFontFam);
//   static const IconData linkedin = const IconData(0xe803, fontFamily: _kFontFam);
//}
